---
apiVersion: v1
kind: Service
metadata:
  name: nginx-np-ext-ip
  labels:
    service: nginx-np-ext-ip
spec:
  type: NodePort
  ports:
  - nodePort: 30480
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
  externalIPs:
    - 10.99.0.2
