---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-ext-ip
  labels:
    service: nginx-lb-ext-ip
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
  externalIPs:
    - 10.99.0.1
  externalTrafficPolicy: Local
