---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-auto-ip
  labels:
    service: nginx-lb-auto-ip
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
