---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-auto-ip-local
  labels:
    service: nginx-lb-auto-ip-local
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
  externalTrafficPolicy: Local
