apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: false
  serviceClusterIPs:
  - cidr: 10.49.0.0/16
  serviceExternalIPs:
  - cidr: 10.99.0.0/16
  serviceLoadBalancerIPs:
  - cidr: 10.100.0.0/16
