---
apiVersion: v1
kind: Service
metadata:
  name: nginx-np-ext-traf-pol-cluster
  labels:
    service: nginx-np-ext-traf-pol-cluster
spec:
  ports:
  - nodePort: 30482
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
  type: NodePort
  externalTrafficPolicy: Cluster
