---
apiVersion: v1
kind: Service
metadata:
  name: nginx-np
  labels:
    service: nginx-np
spec:
  ports:
  - nodePort: 30480
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
  type: NodePort
  #externalTrafficPolicy: Local
